### ISSUE TITLE
3D display with NGL, TODO

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#144]
What remains to be done before release:
- [ ] Upgrade to latest NGL
- [x] Add instructions on how to show surfaces (pressing p and n), as a minimal solution for #126 
- [x] Add instructions on how to take snapshots (pressing s, m, l)

**Comment by josemduarte** [comment]
Added the help box and some legend. Could not upgrade to latest ngl because of issue https://github.com/arose/ngl/issues/252. We'll have to wait for next release
